// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/email/email.proto

package kindle_service_email

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateEmailRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailRequest) Reset()         { *m = CreateEmailRequest{} }
func (m *CreateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEmailRequest) ProtoMessage()    {}
func (*CreateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_840f7b8354a62044, []int{0}
}

func (m *CreateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailRequest.Unmarshal(m, b)
}
func (m *CreateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailRequest.Marshal(b, m, deterministic)
}
func (m *CreateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailRequest.Merge(m, src)
}
func (m *CreateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEmailRequest.Size(m)
}
func (m *CreateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailRequest proto.InternalMessageInfo

func (m *CreateEmailRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateEmailResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailResponse) Reset()         { *m = CreateEmailResponse{} }
func (m *CreateEmailResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEmailResponse) ProtoMessage()    {}
func (*CreateEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_840f7b8354a62044, []int{1}
}

func (m *CreateEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailResponse.Unmarshal(m, b)
}
func (m *CreateEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailResponse.Marshal(b, m, deterministic)
}
func (m *CreateEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailResponse.Merge(m, src)
}
func (m *CreateEmailResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEmailResponse.Size(m)
}
func (m *CreateEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailResponse proto.InternalMessageInfo

func (m *CreateEmailResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateEmailResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateEmailRequest)(nil), "kindle.service.email.CreateEmailRequest")
	proto.RegisterType((*CreateEmailResponse)(nil), "kindle.service.email.CreateEmailResponse")
}

func init() { proto.RegisterFile("proto/email/email.proto", fileDescriptor_840f7b8354a62044) }

var fileDescriptor_840f7b8354a62044 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcd, 0x4d, 0xcc, 0xcc, 0x81, 0x90, 0x7a, 0x60, 0x11, 0x21, 0x91, 0xec, 0xcc,
	0xbc, 0x94, 0x9c, 0x54, 0xbd, 0xe2, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x3d, 0xb0, 0x9c, 0x92,
	0x13, 0x97, 0x90, 0x73, 0x51, 0x6a, 0x62, 0x49, 0xaa, 0x2b, 0x88, 0x1b, 0x94, 0x5a, 0x58, 0x9a,
	0x5a, 0x5c, 0x22, 0x24, 0xc6, 0xc5, 0x16, 0x5a, 0x9c, 0x5a, 0xe4, 0x99, 0x22, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x1a, 0x04, 0xe5, 0x09, 0x89, 0x70, 0xb1, 0x82, 0xd5, 0x49, 0x30, 0x29, 0x30, 0x6a,
	0x70, 0x06, 0x41, 0x38, 0x4a, 0xd6, 0x5c, 0xc2, 0x28, 0x66, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7,
	0x0a, 0x09, 0x71, 0xb1, 0x38, 0xe7, 0xa7, 0xa4, 0x42, 0x8d, 0x00, 0xb3, 0x85, 0x04, 0xb8, 0x98,
	0x7d, 0x8b, 0xd3, 0xa1, 0xda, 0x41, 0x4c, 0xa3, 0x12, 0x2e, 0x1e, 0xb0, 0xb6, 0x60, 0x88, 0xb3,
	0x84, 0x52, 0xb8, 0xb8, 0x91, 0x0c, 0x13, 0xd2, 0xd0, 0xc3, 0xe6, 0x6c, 0x3d, 0x4c, 0x37, 0x4b,
	0x69, 0x12, 0xa1, 0x12, 0xe2, 0x32, 0x25, 0x86, 0x24, 0x36, 0x70, 0x98, 0x18, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xa4, 0x69, 0x9b, 0xdf, 0x2e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailServiceClient is the client API for EmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailServiceClient interface {
	CreateEmail(ctx context.Context, in *CreateEmailRequest, opts ...grpc.CallOption) (*CreateEmailResponse, error)
}

type emailServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmailServiceClient(cc *grpc.ClientConn) EmailServiceClient {
	return &emailServiceClient{cc}
}

func (c *emailServiceClient) CreateEmail(ctx context.Context, in *CreateEmailRequest, opts ...grpc.CallOption) (*CreateEmailResponse, error) {
	out := new(CreateEmailResponse)
	err := c.cc.Invoke(ctx, "/kindle.service.email.EmailService/CreateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServiceServer is the server API for EmailService service.
type EmailServiceServer interface {
	CreateEmail(context.Context, *CreateEmailRequest) (*CreateEmailResponse, error)
}

func RegisterEmailServiceServer(s *grpc.Server, srv EmailServiceServer) {
	s.RegisterService(&_EmailService_serviceDesc, srv)
}

func _EmailService_CreateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).CreateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kindle.service.email.EmailService/CreateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).CreateEmail(ctx, req.(*CreateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kindle.service.email.EmailService",
	HandlerType: (*EmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEmail",
			Handler:    _EmailService_CreateEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/email/email.proto",
}
