[kloveconf]
	ServerAddr = "0.0.0.0"
	ServerPort = 8080

[sessionconf]
    SessionIDLength = 32
	CookieLifeTime = 65525
	CookieName = "KSID"
	GcTime = 65525
	Domain = ".poetnote.com"
	handlerType = "file"
	filePath = "storage/session"