// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/email.proto

package kindle_service_email

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateEmailRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailRequest) Reset()         { *m = CreateEmailRequest{} }
func (m *CreateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEmailRequest) ProtoMessage()    {}
func (*CreateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{0}
}

func (m *CreateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailRequest.Unmarshal(m, b)
}
func (m *CreateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailRequest.Marshal(b, m, deterministic)
}
func (m *CreateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailRequest.Merge(m, src)
}
func (m *CreateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEmailRequest.Size(m)
}
func (m *CreateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailRequest proto.InternalMessageInfo

func (m *CreateEmailRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateEmailResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailResponse) Reset()         { *m = CreateEmailResponse{} }
func (m *CreateEmailResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEmailResponse) ProtoMessage()    {}
func (*CreateEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{1}
}

func (m *CreateEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailResponse.Unmarshal(m, b)
}
func (m *CreateEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailResponse.Marshal(b, m, deterministic)
}
func (m *CreateEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailResponse.Merge(m, src)
}
func (m *CreateEmailResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEmailResponse.Size(m)
}
func (m *CreateEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailResponse proto.InternalMessageInfo

func (m *CreateEmailResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateEmailResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type EditEmailRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditEmailRequest) Reset()         { *m = EditEmailRequest{} }
func (m *EditEmailRequest) String() string { return proto.CompactTextString(m) }
func (*EditEmailRequest) ProtoMessage()    {}
func (*EditEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{2}
}

func (m *EditEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditEmailRequest.Unmarshal(m, b)
}
func (m *EditEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditEmailRequest.Marshal(b, m, deterministic)
}
func (m *EditEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditEmailRequest.Merge(m, src)
}
func (m *EditEmailRequest) XXX_Size() int {
	return xxx_messageInfo_EditEmailRequest.Size(m)
}
func (m *EditEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditEmailRequest proto.InternalMessageInfo

func (m *EditEmailRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EditEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type EditEmailResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditEmailResponse) Reset()         { *m = EditEmailResponse{} }
func (m *EditEmailResponse) String() string { return proto.CompactTextString(m) }
func (*EditEmailResponse) ProtoMessage()    {}
func (*EditEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{3}
}

func (m *EditEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditEmailResponse.Unmarshal(m, b)
}
func (m *EditEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditEmailResponse.Marshal(b, m, deterministic)
}
func (m *EditEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditEmailResponse.Merge(m, src)
}
func (m *EditEmailResponse) XXX_Size() int {
	return xxx_messageInfo_EditEmailResponse.Size(m)
}
func (m *EditEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditEmailResponse proto.InternalMessageInfo

func (m *EditEmailResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *EditEmailResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 发送请求
type CreateRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	File                 string   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{4}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateRequest) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

// 发送回报
type CreateResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{5}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 查询请求
type SelectRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectRequest) Reset()         { *m = SelectRequest{} }
func (m *SelectRequest) String() string { return proto.CompactTextString(m) }
func (*SelectRequest) ProtoMessage()    {}
func (*SelectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{6}
}

func (m *SelectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectRequest.Unmarshal(m, b)
}
func (m *SelectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectRequest.Marshal(b, m, deterministic)
}
func (m *SelectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectRequest.Merge(m, src)
}
func (m *SelectRequest) XXX_Size() int {
	return xxx_messageInfo_SelectRequest.Size(m)
}
func (m *SelectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectRequest proto.InternalMessageInfo

func (m *SelectRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SelectRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SelectRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

// email数据
type Email struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ToEmail              string   `protobuf:"bytes,3,opt,name=ToEmail,proto3" json:"ToEmail,omitempty"`
	FilePath             string   `protobuf:"bytes,4,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{7}
}

func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (m *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(m, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Email) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Email) GetToEmail() string {
	if m != nil {
		return m.ToEmail
	}
	return ""
}

func (m *Email) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *Email) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Email) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// 查询回报
type SelectResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
	Data                 []*Email `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectResponse) Reset()         { *m = SelectResponse{} }
func (m *SelectResponse) String() string { return proto.CompactTextString(m) }
func (*SelectResponse) ProtoMessage()    {}
func (*SelectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{8}
}

func (m *SelectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectResponse.Unmarshal(m, b)
}
func (m *SelectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectResponse.Marshal(b, m, deterministic)
}
func (m *SelectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectResponse.Merge(m, src)
}
func (m *SelectResponse) XXX_Size() int {
	return xxx_messageInfo_SelectResponse.Size(m)
}
func (m *SelectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SelectResponse proto.InternalMessageInfo

func (m *SelectResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SelectResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SelectResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *SelectResponse) GetData() []*Email {
	if m != nil {
		return m.Data
	}
	return nil
}

// 删除请求
type DeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{9}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 删除回报
type DeleteResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{10}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateEmailRequest)(nil), "kindle.service.email.CreateEmailRequest")
	proto.RegisterType((*CreateEmailResponse)(nil), "kindle.service.email.CreateEmailResponse")
	proto.RegisterType((*EditEmailRequest)(nil), "kindle.service.email.EditEmailRequest")
	proto.RegisterType((*EditEmailResponse)(nil), "kindle.service.email.EditEmailResponse")
	proto.RegisterType((*CreateRequest)(nil), "kindle.service.email.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "kindle.service.email.CreateResponse")
	proto.RegisterType((*SelectRequest)(nil), "kindle.service.email.SelectRequest")
	proto.RegisterType((*Email)(nil), "kindle.service.email.Email")
	proto.RegisterType((*SelectResponse)(nil), "kindle.service.email.SelectResponse")
	proto.RegisterType((*DeleteRequest)(nil), "kindle.service.email.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "kindle.service.email.DeleteResponse")
}

func init() { proto.RegisterFile("proto/email.proto", fileDescriptor_90f7cc01862a1851) }

var fileDescriptor_90f7cc01862a1851 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x8e, 0xd3, 0x40,
	0x0c, 0xde, 0x66, 0xd2, 0x40, 0xbd, 0xb4, 0xda, 0x35, 0x2b, 0x14, 0x15, 0x24, 0x56, 0x03, 0x82,
	0x72, 0xc9, 0x4a, 0x8b, 0x84, 0x40, 0x7b, 0x82, 0xb6, 0x48, 0x48, 0x20, 0x95, 0x94, 0x5e, 0x91,
	0x42, 0x63, 0xca, 0x88, 0xb4, 0x29, 0xc9, 0x94, 0x1b, 0x0f, 0xc3, 0x63, 0xf1, 0x36, 0x68, 0x66,
	0xf2, 0xd3, 0x6c, 0x9b, 0xfe, 0xdc, 0xec, 0xd8, 0xfe, 0x3e, 0xfb, 0xb3, 0x27, 0x70, 0xbe, 0x4c,
	0x62, 0x19, 0x5f, 0xd1, 0x3c, 0x10, 0x91, 0xa7, 0x6d, 0xbc, 0xf8, 0x29, 0x16, 0x61, 0x44, 0x5e,
	0x4a, 0xc9, 0x6f, 0x31, 0x25, 0x4f, 0xc7, 0xf8, 0x3b, 0xc0, 0x7e, 0x42, 0x81, 0xa4, 0xa1, 0x72,
	0x7d, 0xfa, 0xb5, 0xa2, 0x54, 0xe2, 0x03, 0x70, 0x26, 0x29, 0x25, 0x1f, 0x42, 0xb7, 0x71, 0xd9,
	0xe8, 0xb5, 0xfc, 0xcc, 0xc3, 0x0b, 0x68, 0xea, 0x3c, 0xd7, 0xd2, 0x9f, 0x8d, 0xc3, 0x6f, 0xe0,
	0x7e, 0x05, 0x23, 0x5d, 0xc6, 0x8b, 0x94, 0x10, 0xc1, 0xee, 0xc7, 0x21, 0x69, 0x88, 0xa6, 0xaf,
	0x6d, 0x3c, 0x03, 0xf6, 0x29, 0x9d, 0x65, 0xe5, 0xca, 0xe4, 0xaf, 0xe1, 0x6c, 0x18, 0x0a, 0x59,
	0xa1, 0xef, 0x80, 0x55, 0x50, 0x5b, 0xb5, 0xb4, 0x6f, 0xe0, 0x7c, 0xad, 0xf2, 0x28, 0xd2, 0x1b,
	0x68, 0x9b, 0x8e, 0xf7, 0x0d, 0x8c, 0x60, 0x7f, 0x17, 0x11, 0x65, 0xb5, 0xda, 0xe6, 0xaf, 0xa0,
	0x93, 0x17, 0x6f, 0x21, 0x65, 0xb5, 0xa4, 0x9f, 0xa1, 0x3d, 0xa6, 0x88, 0xa6, 0xf2, 0x00, 0x95,
	0x3f, 0x8a, 0xb9, 0x90, 0xba, 0x98, 0xf9, 0xc6, 0x51, 0x24, 0xa3, 0x60, 0x46, 0x2e, 0x33, 0x24,
	0xca, 0xe6, 0x7f, 0x1b, 0x99, 0x32, 0x1b, 0x92, 0x95, 0xd8, 0x56, 0x05, 0xdb, 0x85, 0x3b, 0x5f,
	0x62, 0x23, 0x26, 0xd3, 0x81, 0xdc, 0xc5, 0x2e, 0xdc, 0x7d, 0x2f, 0x22, 0x1a, 0x05, 0xf2, 0x87,
	0x6b, 0xeb, 0x50, 0xe1, 0xe3, 0x23, 0x68, 0x99, 0x91, 0xc3, 0xb7, 0xd2, 0x6d, 0xea, 0x60, 0xf9,
	0x41, 0x45, 0x27, 0xcb, 0x30, 0x8b, 0x3a, 0x26, 0x5a, 0x7c, 0xe0, 0x7f, 0xa0, 0x93, 0x8f, 0x7d,
	0x8c, 0x5c, 0x4a, 0x85, 0x7e, 0xbc, 0x5a, 0xc8, 0x6c, 0x60, 0xe3, 0xe0, 0x15, 0xd8, 0x83, 0x40,
	0x06, 0xae, 0x7d, 0xc9, 0x7a, 0xa7, 0xd7, 0x0f, 0xbd, 0x6d, 0x47, 0xed, 0x99, 0x93, 0xd0, 0x89,
	0xfc, 0x31, 0xb4, 0x07, 0x14, 0x51, 0xb9, 0xea, 0x52, 0x29, 0xa6, 0x94, 0x52, 0xeb, 0xcc, 0x13,
	0x8e, 0xe9, 0xef, 0xfa, 0x1f, 0x83, 0x7b, 0x9a, 0x68, 0x6c, 0xb8, 0x31, 0x84, 0xd3, 0xb5, 0x67,
	0x80, 0xbd, 0xed, 0xbd, 0x6d, 0xbe, 0xb6, 0xee, 0x8b, 0x03, 0x32, 0x4d, 0x6b, 0xfc, 0x04, 0xbf,
	0x42, 0xab, 0xb8, 0x7a, 0x7c, 0x56, 0x33, 0xff, 0xad, 0x07, 0xd5, 0x7d, 0xbe, 0x37, 0xaf, 0xc0,
	0x9f, 0x80, 0x63, 0x88, 0xf1, 0xc9, 0xae, 0xb6, 0x72, 0xe4, 0xa7, 0xbb, 0x93, 0xd6, 0x61, 0xcd,
	0x15, 0xd4, 0xc1, 0x56, 0x9e, 0x46, 0x1d, 0x6c, 0xf5, 0x90, 0x0c, 0xac, 0x59, 0x5e, 0x1d, 0x6c,
	0x65, 0xf7, 0x75, 0xb0, 0xd5, 0xfd, 0xf3, 0x93, 0x6f, 0x8e, 0xfe, 0x65, 0xbe, 0xfc, 0x1f, 0x00,
	0x00, 0xff, 0xff, 0xa4, 0x3c, 0x08, 0xa8, 0x47, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailServiceClient is the client API for EmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailServiceClient interface {
	CreateEmail(ctx context.Context, in *CreateEmailRequest, opts ...grpc.CallOption) (*CreateEmailResponse, error)
	EditEmail(ctx context.Context, in *EditEmailRequest, opts ...grpc.CallOption) (*EditEmailResponse, error)
	// 1.发送
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// 2.查询
	Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error)
	// 3.删除某一条
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type emailServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmailServiceClient(cc *grpc.ClientConn) EmailServiceClient {
	return &emailServiceClient{cc}
}

func (c *emailServiceClient) CreateEmail(ctx context.Context, in *CreateEmailRequest, opts ...grpc.CallOption) (*CreateEmailResponse, error) {
	out := new(CreateEmailResponse)
	err := c.cc.Invoke(ctx, "/kindle.service.email.EmailService/CreateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) EditEmail(ctx context.Context, in *EditEmailRequest, opts ...grpc.CallOption) (*EditEmailResponse, error) {
	out := new(EditEmailResponse)
	err := c.cc.Invoke(ctx, "/kindle.service.email.EmailService/EditEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/kindle.service.email.EmailService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error) {
	out := new(SelectResponse)
	err := c.cc.Invoke(ctx, "/kindle.service.email.EmailService/Select", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/kindle.service.email.EmailService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServiceServer is the server API for EmailService service.
type EmailServiceServer interface {
	CreateEmail(context.Context, *CreateEmailRequest) (*CreateEmailResponse, error)
	EditEmail(context.Context, *EditEmailRequest) (*EditEmailResponse, error)
	// 1.发送
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// 2.查询
	Select(context.Context, *SelectRequest) (*SelectResponse, error)
	// 3.删除某一条
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterEmailServiceServer(s *grpc.Server, srv EmailServiceServer) {
	s.RegisterService(&_EmailService_serviceDesc, srv)
}

func _EmailService_CreateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).CreateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kindle.service.email.EmailService/CreateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).CreateEmail(ctx, req.(*CreateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_EditEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).EditEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kindle.service.email.EmailService/EditEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).EditEmail(ctx, req.(*EditEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kindle.service.email.EmailService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_Select_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).Select(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kindle.service.email.EmailService/Select",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).Select(ctx, req.(*SelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kindle.service.email.EmailService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kindle.service.email.EmailService",
	HandlerType: (*EmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEmail",
			Handler:    _EmailService_CreateEmail_Handler,
		},
		{
			MethodName: "EditEmail",
			Handler:    _EmailService_EditEmail_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _EmailService_Create_Handler,
		},
		{
			MethodName: "Select",
			Handler:    _EmailService_Select_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EmailService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/email.proto",
}
