// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/email.proto

package poetnote_service_email

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 邮箱结构
type EmailAddr struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailAddr) Reset()         { *m = EmailAddr{} }
func (m *EmailAddr) String() string { return proto.CompactTextString(m) }
func (*EmailAddr) ProtoMessage()    {}
func (*EmailAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{0}
}

func (m *EmailAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailAddr.Unmarshal(m, b)
}
func (m *EmailAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailAddr.Marshal(b, m, deterministic)
}
func (m *EmailAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailAddr.Merge(m, src)
}
func (m *EmailAddr) XXX_Size() int {
	return xxx_messageInfo_EmailAddr.Size(m)
}
func (m *EmailAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailAddr.DiscardUnknown(m)
}

var xxx_messageInfo_EmailAddr proto.InternalMessageInfo

func (m *EmailAddr) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *EmailAddr) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// 发送请求
type CreateRequest struct {
	From                 *EmailAddr   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	FromPasswd           string       `protobuf:"bytes,2,opt,name=fromPasswd,proto3" json:"fromPasswd,omitempty"`
	To                   []*EmailAddr `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	Title                string       `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string       `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	File                 string       `protobuf:"bytes,6,opt,name=file,proto3" json:"file,omitempty"`
	UserId               string       `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetFrom() *EmailAddr {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *CreateRequest) GetFromPasswd() string {
	if m != nil {
		return m.FromPasswd
	}
	return ""
}

func (m *CreateRequest) GetTo() []*EmailAddr {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *CreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CreateRequest) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *CreateRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// 发送回报
type CreateResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 查询请求
type SelectRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectRequest) Reset()         { *m = SelectRequest{} }
func (m *SelectRequest) String() string { return proto.CompactTextString(m) }
func (*SelectRequest) ProtoMessage()    {}
func (*SelectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{3}
}

func (m *SelectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectRequest.Unmarshal(m, b)
}
func (m *SelectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectRequest.Marshal(b, m, deterministic)
}
func (m *SelectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectRequest.Merge(m, src)
}
func (m *SelectRequest) XXX_Size() int {
	return xxx_messageInfo_SelectRequest.Size(m)
}
func (m *SelectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectRequest proto.InternalMessageInfo

func (m *SelectRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SelectRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SelectRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

// email数据
type Email struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	From                 *EmailAddr   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	UserId               string       `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	To                   []*EmailAddr `protobuf:"bytes,4,rep,name=to,proto3" json:"to,omitempty"`
	Title                string       `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string       `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	File                 string       `protobuf:"bytes,7,opt,name=file,proto3" json:"file,omitempty"`
	CreateTime           string       `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{4}
}

func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (m *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(m, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Email) GetFrom() *EmailAddr {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Email) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Email) GetTo() []*EmailAddr {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Email) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Email) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Email) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *Email) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

// 查询回报
type SelectResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	List                 []*Email `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectResponse) Reset()         { *m = SelectResponse{} }
func (m *SelectResponse) String() string { return proto.CompactTextString(m) }
func (*SelectResponse) ProtoMessage()    {}
func (*SelectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{5}
}

func (m *SelectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectResponse.Unmarshal(m, b)
}
func (m *SelectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectResponse.Marshal(b, m, deterministic)
}
func (m *SelectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectResponse.Merge(m, src)
}
func (m *SelectResponse) XXX_Size() int {
	return xxx_messageInfo_SelectResponse.Size(m)
}
func (m *SelectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SelectResponse proto.InternalMessageInfo

func (m *SelectResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SelectResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SelectResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *SelectResponse) GetList() []*Email {
	if m != nil {
		return m.List
	}
	return nil
}

// 删除请求
type DeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{6}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 删除回报
type DeleteResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{7}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*EmailAddr)(nil), "poetnote.service.email.EmailAddr")
	proto.RegisterType((*CreateRequest)(nil), "poetnote.service.email.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "poetnote.service.email.CreateResponse")
	proto.RegisterType((*SelectRequest)(nil), "poetnote.service.email.SelectRequest")
	proto.RegisterType((*Email)(nil), "poetnote.service.email.Email")
	proto.RegisterType((*SelectResponse)(nil), "poetnote.service.email.SelectResponse")
	proto.RegisterType((*DeleteRequest)(nil), "poetnote.service.email.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "poetnote.service.email.DeleteResponse")
}

func init() { proto.RegisterFile("proto/email.proto", fileDescriptor_90f7cc01862a1851) }

var fileDescriptor_90f7cc01862a1851 = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x5f, 0xe2, 0x34, 0x65, 0x6f, 0xb4, 0x02, 0x0b, 0x81, 0x85, 0x04, 0x1b, 0x96, 0x40, 0x9c,
	0x82, 0x36, 0x34, 0xee, 0x08, 0x38, 0x70, 0x43, 0x1e, 0x17, 0x4e, 0x53, 0x16, 0xbf, 0x4d, 0x96,
	0x92, 0xba, 0xc4, 0x2e, 0x88, 0x13, 0x1f, 0x85, 0xaf, 0xc8, 0x95, 0x1b, 0xf2, 0x73, 0xba, 0x26,
	0xa8, 0x01, 0xba, 0x53, 0x9f, 0x5f, 0xed, 0xdf, 0xbf, 0xf7, 0x5a, 0xb8, 0xbb, 0x6c, 0xad, 0xb7,
	0x2f, 0xb0, 0x29, 0x4d, 0x5d, 0x50, 0xcd, 0xef, 0x2f, 0x2d, 0xfa, 0x85, 0xf5, 0x58, 0x38, 0x6c,
	0xbf, 0x98, 0x0a, 0x0b, 0xfa, 0x56, 0x9e, 0xc2, 0xfe, 0xbb, 0x50, 0xbc, 0xd6, 0xba, 0xe5, 0x1c,
	0xb2, 0x52, 0xeb, 0x56, 0x24, 0x47, 0xc9, 0xf3, 0x7d, 0x45, 0x35, 0xbf, 0x07, 0x13, 0x6f, 0x7c,
	0x8d, 0x22, 0xa5, 0x66, 0x3c, 0xc8, 0x9f, 0x09, 0xcc, 0xde, 0xb4, 0x58, 0x7a, 0x54, 0xf8, 0x79,
	0x85, 0xce, 0xf3, 0x53, 0xc8, 0x2e, 0x5b, 0xdb, 0xd0, 0xdb, 0x83, 0x93, 0x27, 0xc5, 0x76, 0xbe,
	0xe2, 0x9a, 0x4c, 0xd1, 0x75, 0xfe, 0x18, 0x20, 0x7c, 0x7e, 0x28, 0x9d, 0xfb, 0xaa, 0x3b, 0x8e,
	0x5e, 0x87, 0x1f, 0x43, 0xea, 0xad, 0x60, 0x47, 0xec, 0xff, 0x40, 0x53, 0x6f, 0x37, 0x8a, 0xb3,
	0x9e, 0xe2, 0xe0, 0xed, 0xc2, 0xea, 0x6f, 0x62, 0x12, 0xbd, 0x85, 0x3a, 0xf4, 0x2e, 0x4d, 0x8d,
	0x22, 0x8f, 0xbd, 0x50, 0xf3, 0x07, 0x30, 0x5d, 0x39, 0x6c, 0xcf, 0x8d, 0x16, 0x53, 0x6a, 0xe7,
	0xe1, 0xf8, 0x5e, 0xcb, 0x57, 0x30, 0x5f, 0x3b, 0x76, 0x4b, 0xbb, 0x70, 0x04, 0x59, 0x59, 0x8d,
	0x64, 0x99, 0x29, 0xaa, 0xf9, 0x1d, 0x60, 0x8d, 0xbb, 0xea, 0x8c, 0x84, 0x52, 0x2a, 0x98, 0x9d,
	0x61, 0x8d, 0x95, 0x5f, 0x27, 0xd5, 0x63, 0x48, 0xfa, 0x0c, 0x41, 0x78, 0x6d, 0x1a, 0xe3, 0xe9,
	0x35, 0x53, 0xf1, 0x10, 0x58, 0x96, 0xe5, 0x15, 0x0a, 0x16, 0x59, 0x42, 0x2d, 0x7f, 0x25, 0x30,
	0x21, 0xd3, 0x7c, 0x0e, 0x69, 0x87, 0xc3, 0x54, 0x6a, 0xf4, 0xf5, 0x18, 0xd2, 0xdd, 0xc6, 0xd0,
	0xd3, 0xc4, 0x06, 0x9a, 0x62, 0xfe, 0xd9, 0x8d, 0xf2, 0x9f, 0x6c, 0xcb, 0x3f, 0xdf, 0x92, 0xff,
	0xb4, 0x97, 0xff, 0x21, 0x1c, 0x54, 0x14, 0xf3, 0xb9, 0x37, 0x0d, 0x8a, 0x5b, 0x71, 0x23, 0x62,
	0xeb, 0xa3, 0x69, 0x50, 0x7e, 0x87, 0xf9, 0x3a, 0xcf, 0x5d, 0xe6, 0x10, 0x64, 0x55, 0x76, 0xb5,
	0xf0, 0x5d, 0x90, 0xf1, 0xc0, 0x8f, 0x21, 0xab, 0x8d, 0xf3, 0x9d, 0xc3, 0x47, 0x7f, 0x75, 0xa8,
	0xe8, 0xaa, 0x3c, 0x84, 0xd9, 0x5b, 0xac, 0x71, 0xb3, 0xfa, 0x7f, 0xcc, 0x20, 0x6c, 0xca, 0xfa,
	0xc2, 0x2e, 0x0a, 0x4f, 0x7e, 0xa4, 0x70, 0x9b, 0x88, 0xce, 0x22, 0x37, 0xff, 0x04, 0x79, 0x5c,
	0x39, 0xfe, 0x74, 0x4c, 0xd8, 0xe0, 0x47, 0xf8, 0xf0, 0xd9, 0xbf, 0xae, 0x45, 0x3d, 0x72, 0x2f,
	0x40, 0xc7, 0x14, 0xc7, 0xa1, 0x07, 0x5b, 0x3b, 0x0e, 0x3d, 0x1c, 0x46, 0x84, 0x8e, 0xf6, 0xc7,
	0xa1, 0x07, 0xf9, 0x8d, 0x43, 0x0f, 0x53, 0x94, 0x7b, 0x17, 0x39, 0xfd, 0x99, 0xbd, 0xfc, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x5c, 0xa7, 0xac, 0xb4, 0xe1, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for EmailService service

type EmailServiceClient interface {
	// 1.发送
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	// 2.查询
	Select(ctx context.Context, in *SelectRequest, opts ...client.CallOption) (*SelectResponse, error)
	// 3.删除某一条
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
}

type emailServiceClient struct {
	c           client.Client
	serviceName string
}

func NewEmailServiceClient(serviceName string, c client.Client) EmailServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "poetnote.service.email"
	}
	return &emailServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *emailServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "EmailService.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) Select(ctx context.Context, in *SelectRequest, opts ...client.CallOption) (*SelectResponse, error) {
	req := c.c.NewRequest(c.serviceName, "EmailService.Select", in)
	out := new(SelectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "EmailService.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EmailService service

type EmailServiceHandler interface {
	// 1.发送
	Create(context.Context, *CreateRequest, *CreateResponse) error
	// 2.查询
	Select(context.Context, *SelectRequest, *SelectResponse) error
	// 3.删除某一条
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
}

func RegisterEmailServiceHandler(s server.Server, hdlr EmailServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&EmailService{hdlr}, opts...))
}

type EmailService struct {
	EmailServiceHandler
}

func (h *EmailService) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.EmailServiceHandler.Create(ctx, in, out)
}

func (h *EmailService) Select(ctx context.Context, in *SelectRequest, out *SelectResponse) error {
	return h.EmailServiceHandler.Select(ctx, in, out)
}

func (h *EmailService) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.EmailServiceHandler.Delete(ctx, in, out)
}
